"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y-z_$v5jm)ht9d$qxj)q1ablbx!vk*4-3*4temsfd$%rf7joj4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
     'accounts',
      'csp', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',  # Add CSP middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'relationship_app' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# HTTPS AND SECURITY CONFIGURATION
# ============================================

# HTTPS Redirect Settings
# ======================
# SECURE_SSL_REDIRECT: Redirect all HTTP requests to HTTPS
# IMPORTANT: Set to True in production when you have SSL/TLS certificate
SECURE_SSL_REDIRECT = True

# For development/testing without HTTPS, you can temporarily set this to False
# SECURE_SSL_REDIRECT = False  # Use only during development

# HSTS (HTTP Strict Transport Security) Settings
# =============================================
# SECURE_HSTS_SECONDS: Time in seconds for HSTS policy (31536000 = 1 year)
# HSTS tells browsers to only access the site via HTTPS for the specified time
SECURE_HSTS_SECONDS = 31536000  # 1 year

# SECURE_HSTS_INCLUDE_SUBDOMAINS: Apply HSTS to all subdomains
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_HSTS_PRELOAD: Allow inclusion in browser preload lists
SECURE_HSTS_PRELOAD = True

# Cookie Security Settings
# ========================
# SESSION_COOKIE_SECURE: Send session cookies only over HTTPS
SESSION_COOKIE_SECURE = True

# CSRF_COOKIE_SECURE: Send CSRF cookies only over HTTPS
CSRF_COOKIE_SECURE = True

# Additional Cookie Security
# ==========================
# SESSION_COOKIE_HTTPONLY: Prevent JavaScript access to session cookies
SESSION_COOKIE_HTTPONLY = True

# CSRF_COOKIE_HTTPONLY: Prevent JavaScript access to CSRF cookies
# Note: Some JavaScript frameworks need access to CSRF tokens
CSRF_COOKIE_HTTPONLY = True

# SESSION_COOKIE_SAMESITE: Control when cookies are sent with cross-site requests
# Options: 'Strict', 'Lax', or 'None'
SESSION_COOKIE_SAMESITE = 'Lax'  # Recommended for most sites

# CSRF_COOKIE_SAMESITE: SameSite policy for CSRF cookies
CSRF_COOKIE_SAMESITE = 'Lax'

# Security Headers Configuration
# ==============================
# X_FRAME_OPTIONS: Prevent clickjacking by denying framing
X_FRAME_OPTIONS = 'DENY'

# SECURE_CONTENT_TYPE_NOSNIFF: Prevent MIME type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER: Enable browser XSS filtering
SECURE_BROWSER_XSS_FILTER = True

# Referrer Policy
SECURE_REFERRER_POLICY = 'same-origin'

# Proxy Settings (when behind a proxy/load balancer)
# ==================================================
# If your Django app is behind a proxy/load balancer that terminates SSL,
# you need to configure these settings:
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# Add to the bottom of settings.py
LOGIN_REDIRECT_URL = '/relationship_app/books/'
LOGOUT_REDIRECT_URL = '/relationship_app/login/'
AUTH_USER_MODEL = "accounts.CustomUser"
AUTH_USER_MODEL = 'bookshelf.CustomUser'


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Security middleware settings
SECURE_BROWSER_XSS_FILTER = True  # Enable XSS filtering in browsers
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking by denying frames
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing

# Cookie security (set to True in production with HTTPS)
CSRF_COOKIE_SECURE = True  # Send CSRF cookie only over HTTPS
SESSION_COOKIE_SECURE = True  # Send session cookie only over HTTPS
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF cookie
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie

# HSTS settings (uncomment in production)
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# SSL/HTTPS settings (uncomment in production)
# SECURE_SSL_REDIRECT = True  # Redirect all HTTP to HTTPS
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Referrer policy
SECURE_REFERRER_POLICY = 'same-origin'

# ========================
# CONTENT SECURITY POLICY (CSP)
# ========================

CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'",)  # 'unsafe-inline' for development
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'",)  # For development
CSP_IMG_SRC = ("'self'", "data:",)
CSP_FONT_SRC = ("'self'",)
CSP_CONNECT_SRC = ("'self'",)
CSP_OBJECT_SRC = ("'none'",)
CSP_BASE_URI = ("'self'",)
CSP_FORM_ACTION = ("'self'",)
CSP_FRAME_ANCESTORS = ("'none'",)  # Same as X_FRAME_OPTIONS
CSP_BLOCK_ALL_MIXED_CONTENT = True

# ============================================
# DEVELOPMENT OVERRIDES
# ============================================
# Override security settings for development environment
import sys

# Check if we're in development mode (running tests or runserver)
if 'test' in sys.argv or 'runserver' in sys.argv:
    DEBUG = True
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0  # Disable HSTS for development
    # Relax CSP for development
    CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'")
    

    # Development-specific allowed hosts
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
    
    print("\n" + "="*60)
    print("DEVELOPMENT MODE: Security settings relaxed for testing")
    print("="*60 + "\n")

# ============================================
# ENVIRONMENT VARIABLE CONFIGURATION
# ============================================
# In production, use environment variables for sensitive settings
import os
from django.core.exceptions import ImproperlyConfigured

def get_env_variable(var_name, default=None):
    """Get environment variable or return default/exception."""
    try:
        return os.environ[var_name]
    except KeyError:
        if default is not None:
            return default
        error_msg = f"Set the {var_name} environment variable"
        raise ImproperlyConfigured(error_msg)

# Example: Use environment variable for secret key in production
# SECRET_KEY = get_env_variable('DJANGO_SECRET_KEY')
