from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router for ViewSet (optional)
router = DefaultRouter()
router.register(r'books-viewset', views.BookViewSet, basename='book-viewset')

app_name = 'api'

# URL patterns for generic views
urlpatterns = [
    # ============================================
    # BOOK URLS (Generic Views)
    # ============================================
    
    # List all books
    path('books/', views.BookListView.as_view(), name='book-list'),
    
    # Retrieve specific book
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    
    # Create new book
    path('books/create/', views.BookCreateView.as_view(), name='book-create'),
    
    # Update existing book
    path('books/<int:pk>/update/', views.BookUpdateView.as_view(), name='book-update'),
    
    # Delete book
    path('books/<int:pk>/delete/', views.BookDeleteView.as_view(), name='book-delete'),
    
    # ============================================
    # AUTHOR URLS (Generic Views)
    # ============================================
    
    # List all authors
    path('authors/', views.AuthorListView.as_view(), name='author-list'),
    
    # Retrieve specific author
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    
    # Create new author
    path('authors/create/', views.AuthorCreateView.as_view(), name='author-create'),
    
    # Update existing author
    path('authors/<int:pk>/update/', views.AuthorUpdateView.as_view(), name='author-update'),
    
    # Delete author
    path('authors/<int:pk>/delete/', views.AuthorDeleteView.as_view(), name='author-delete'),
    
    # ============================================
    # CUSTOM VIEW URLS
    # ============================================
    
    # Book statistics
    path('books/stats/', views.BookStatsView.as_view(), name='book-stats'),
    
    # Bulk create books
    path('books/bulk-create/', views.BookBulkCreateView.as_view(), name='book-bulk-create'),
    
    # ============================================
    # VIEWSET URLS (Alternative approach)
    # ============================================
    
    # Include ViewSet URLs
    path('', include(router.urls)),
]

# Additional patterns for ViewSet custom actions
viewset_urls = [
    # These are automatically generated by the router
    
]

# Combine all URL patterns
urlpatterns += viewset_urls
